# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XozqpcOpJEC6x4EFfUTLzrbxtuvtEGoO
"""

# app.py

import streamlit as st
from crud import (
    crear_cliente, obtener_clientes, actualizar_cliente, eliminar_cliente,
    crear_pedido, obtener_pedidos
)
from reporte_utils import generar_reporte_pdf

st.set_page_config(page_title="CRM Pappy's Foods", layout="wide")

st.title("🍗 CRM para Pollerías - Pappy's Foods")

menu = st.sidebar.selectbox("Menú", ["Clientes", "Pedidos", "Reporte PDF"])

# --- CLIENTES ---
if menu == "Clientes":
    st.subheader("Gestión de Clientes")
    nombre = st.text_input("Nombre del cliente")
    celular = st.text_input("Celular")
    correo = st.text_input("Correo")
    if st.button("Agregar Cliente"):
        crear_cliente(nombre, celular, correo)
        st.success("Cliente agregado correctamente")

    st.markdown("---")
    st.subheader("Lista de Clientes")
    clientes = obtener_clientes()
    for c in clientes:
        st.write(f"📌 {c['nombre']} - {c['celular']} ({c['correo']})")

# --- PEDIDOS ---
elif menu == "Pedidos":
    st.subheader("Registro de Pedidos")
    cliente_id = st.number_input("ID del Cliente", min_value=1)
    descripcion = st.text_input("Descripción del pedido")
    if st.button("Crear Pedido"):
        crear_pedido(cliente_id, descripcion)
        st.success("Pedido registrado correctamente")

    st.markdown("---")
    st.subheader("Pedidos Registrados")
    pedidos = obtener_pedidos()
    for p in pedidos:
        st.write(f"📦 Pedido {p['id']} - Cliente {p['cliente_id']}: {p['descripcion']}")

# --- REPORTE PDF ---
elif menu == "Reporte PDF":
    st.subheader("Generar Reporte PDF")
    if st.button("Generar"):
        generar_reporte_pdf()
        st.success("Reporte generado. Verifica tu carpeta.")